[build]
  publish = "out/"
  command = "npm run export"
  environment = { ENV = "netlify" }

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = '''
    public,
    max-age=31536000,
    immutable'''
